name: Uncompress Repository Files

on:
  workflow_dispatch:
  push:

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract archives
        shell: bash
        run: |
          set +e

          find . -type f \
          \( -name "*.zip" -o -name "*.tar.gz" -o -name "*.tgz" \) \
          ! -path "./.git/*" | while IFS= read -r file
          do
            echo "Extracting: $file"

            folder=$(dirname "$file")

            if [[ "$file" == *.zip ]]; then
              unzip -o "$file" -d "$folder" || echo "Failed: $file"

            elif [[ "$file" == *.tar.gz || "$file" == *.tgz ]]; then
              tar -xzf "$file" -C "$folder" || echo "Failed: $file"
            fi
          done
